apiVersion: v1
kind: ConfigMap
metadata:
  name: acs-auth-roles
  namespace: stackrox
data:
  authroles.yaml: |
    ---
    Admin:
    - acsadmins
    Analysts:
    - acsanalysts
    Continuous Integration:
    - acsci
