apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-config-auth-app
  labels:
    gitops.ownedBy: acs-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: stackrox
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/auth
    repoURL: https://github.com/caseyrobb/rhacs-config-gitops
    targetRevision: master
  project: acs-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
